version: build-{build}-{branch}

environment:
  global:
   AIO: pygi-aio-3.24.1_rev1-setup_049a323fe25432b10f7e9f543b74598d4be74a39.exe
   STOCKFISH: stockfish-windows-amd64.exe

  matrix:
    # http://www.appveyor.com/docs/installed-software#python lists available
    # versions
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x" # currently 3.4.4
      PYTHON_ARCH: "32"

init:
  - "echo %PYTHON%"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  # - "pip install --disable-pip-version-check --user --upgrade pip"
  - "pip install pexpect"
  - "pip install psutil"
  - "pip install sqlalchemy"

  # Download pygobjectwin32
  - "if not exist %AIO% appveyor DownloadFile https://sourceforge.net/projects/pygobjectwin32/files/%AIO%"
  - "if not exist %PYTHON%\\lib\\site-packages\\gi %AIO% %PYTHON% GDKPixbuf GTK GTKSourceView Pango"

  # ownload stockfish
  - "if not exist c:\\projects\\pychess\\engines mkdir c:\\projects\\pychess\\engines"
  - "if not exist c:\\projects\\pychess\\engines\\%STOCKFISH% appveyor DownloadFile https://github.com/niklasf/Stockfish/releases/download/fishnet-170318/%STOCKFISH% -FileName c:\\projects\\pychess\\engines\\stockfish_9_x64.exe"
  - dir c:\projects\pychess\engines

cache:
  - "%AIO%"
  # - "%PYTHON%\\lib\\site-packages"
  - "c:\\projects\\pychess\\engines"

build_script:
  - "python setup.py build sdist"

test_script:
 - cd testing
 # print(board) needs this in Windows console (before Python 3.6)
 - set PYTHONIOENCODING=utf8
 - set PYTHONPATH=../lib
 - python -m unittest discover -p "*.py"
